// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEDSxavaBwBv4ONZMGhLph4NJCl026isg',
    appId: '1:430525614074:web:81c44050058bb4b1fec643',
    messagingSenderId: '430525614074',
    projectId: 'cityhero-88332',
    authDomain: 'cityhero-88332.firebaseapp.com',
    storageBucket: 'cityhero-88332.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCHvI3se6uD5x0w7OuQufmzc5Q6zrSkho',
    appId: '1:430525614074:android:1a4828b1bcd4ea87fec643',
    messagingSenderId: '430525614074',
    projectId: 'cityhero-88332',
    storageBucket: 'cityhero-88332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5FWBuTgDOfAne0bE1-qJ3naCDzncw40g',
    appId: '1:430525614074:ios:a0ec4badaa16fee3fec643',
    messagingSenderId: '430525614074',
    projectId: 'cityhero-88332',
    storageBucket: 'cityhero-88332.appspot.com',
    iosClientId: '430525614074-k04k09bdurqs0kbk0a91cit49782423j.apps.googleusercontent.com',
    iosBundleId: 'groupb.members.cityHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5FWBuTgDOfAne0bE1-qJ3naCDzncw40g',
    appId: '1:430525614074:ios:0488d6fae2eb27b0fec643',
    messagingSenderId: '430525614074',
    projectId: 'cityhero-88332',
    storageBucket: 'cityhero-88332.appspot.com',
    iosClientId: '430525614074-5v5f4jc4nti6dsjg7putpbl98tnr1369.apps.googleusercontent.com',
    iosBundleId: 'groupb.members.cityHero.RunnerTests',
  );
}
